# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ViridiaMonitoring

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://viridiaregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4965fa1a3be14e9780604c529162d66d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_afcfcce3caac4a73875d558b2de19395 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: viridiaregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4965fa1a3be14e9780604c529162d66d }}/viridiamonitor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ViridiaMonitoring'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5b4c44e1ffb64d9d9b4dee2eaf10f642 }}
        images: 'viridiaregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4965fa1a3be14e9780604c529162d66d }}/viridiamonitor:${{ github.sha }}'